version: "3.8"

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -c "
       /opt/spark/sbin/start-master.sh &&
        tail -f /opt/spark/logs/*"
    environment:
      - SPARK_LOCAL_DIRS=/tmp/spark
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    command: >
      bash -c "
       mkdir -p /data/cleaned && chmod -R 777 /data/cleaned || true &&
       /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/*"
    environment:
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - PYTHONPATH=/opt/app
      - SPARK_LOCAL_DIRS=/tmp/spark
    volumes:
      - ./src:/opt/app/src
      - ./data/raw:/data/raw
      - ./data/cleaned:/data/cleaned
    networks:
      - spark-net
    user: root

  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    command: >
      bash -c "
       mkdir -p /data/cleaned && chmod -R 777 /data/cleaned || true &&
       /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/*"
    environment:
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - PYTHONPATH=/opt/app
      - SPARK_LOCAL_DIRS=/tmp/spark
    volumes:
      - ./src:/opt/app/src
      - ./data/raw:/data/raw
      - ./data/cleaned:/data/cleaned
    networks:
      - spark-net
    user: root

  jupyter:
    image: jupyter/all-spark-notebook:x86_64-spark-3.5.0
    container_name: spark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./jobs:/home/jovyan/work
      - ./src:/opt/app/src
      - ./data/raw:/data/raw
      - ./data/cleaned:/data/cleaned
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYTHONPATH=/opt/app
      - SPARK_LOCAL_DIRS=/tmp/spark
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    networks:
      - spark-net
    user: root

networks:
  spark-net:
    driver: bridge